apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warlords-data
  namespace: warlords
  labels:
    app: warlords
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
