apiVersion: v1
kind: Service
metadata: 
  name: warlords
  namespace: warlords
  labels:
    app: warlords
spec: 
  selector: 
    app: warlords
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      