// Production entry: one Node process serving the SPA (adapter-node handler),
// the save API, and — from M3 — the /ws endpoint. Node 26 runs this file
// directly via built-in type stripping; locally use `npm run start`.
import { createServer } from 'node:http';
import { join, dirname } from 'node:path';
import { mkdirSync } from 'node:fs';
import { openDb } from './db.ts';
import { createApi } from './api.ts';
import { RoomRegistry } from './rooms.ts';
import { attachWebSocketServer } from './ws.ts';

const DATABASE_PATH = process.env.DATABASE_PATH ?? 'data/warlords.db';
const PORT = Number(process.env.PORT ?? 3000);
const BACKUP_INTERVAL_MS = 24 * 60 * 60 * 1000;

const db = openDb(DATABASE_PATH);
const api = createApi(db);

// Generated by `npm run build` (adapter-node); not present in dev/test.
// @ts-ignore
const { handler } = await import('../build/handler.js');

const server = createServer((req, res) => {
  api(req, res, () => handler(req, res));
});
const rooms = new RoomRegistry(db);
const wsService = attachWebSocketServer(server, db, rooms);

server.listen(PORT, () => {
  console.log(`warlords listening on :${PORT}, db at ${DATABASE_PATH}`);
});

// Daily backup ring on the data volume: one file per weekday, overwritten
// weekly. Off-volume shipping is a follow-up (parent plan, deployment).
async function backup(): Promise<void> {
  const dir = join(dirname(DATABASE_PATH), 'backup');
  mkdirSync(dir, { recursive: true });
  const day = new Date().toLocaleDateString('en-US', { weekday: 'short' }).toLowerCase();
  const dest = join(dir, `warlords-${day}.db`);
  try {
    await db.backup(dest);
    console.log(`backup written: ${dest}`);
  } catch (err) {
    console.error('backup failed:', err);
  }
}
void backup();
const backupTimer = setInterval(backup, BACKUP_INTERVAL_MS);

// Recreate rollouts SIGTERM this process on every deploy. Drain in-flight
// requests and close the database cleanly so the next pod opens a settled file.
for (const signal of ['SIGTERM', 'SIGINT'] as const) {
  process.on(signal, () => {
    console.log(`${signal} received, shutting down`);
    clearInterval(backupTimer);
    void wsService.close().then(() => {
      server.close(() => {
        db.close();
        process.exit(0);
      });
    });
    setTimeout(() => process.exit(0), 10_000).unref();
  });
}
