CREATE TABLE players (
  id         TEXT PRIMARY KEY,
  token      TEXT NOT NULL UNIQUE,
  created_at INTEGER NOT NULL
);

-- Same key/value shape the idb layer used, but per-player and typed by slot.
-- slot: 'hero' | 'campaign' | 'gauntletRun'
CREATE TABLE saves (
  player_id  TEXT NOT NULL REFERENCES players(id),
  slot       TEXT NOT NULL,
  data       TEXT NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (player_id, slot)
);

-- One row per battle (solo and co-op). initial_state is the full BattleState
-- snapshot at combat start (post-deploy, log stripped); it embeds the seed,
-- which is what makes the action log replayable.
CREATE TABLE battles (
  id             TEXT PRIMARY KEY,
  mode           TEXT NOT NULL,
  player_ids     TEXT NOT NULL,
  initial_state  TEXT NOT NULL,
  engine_version TEXT NOT NULL,
  result         TEXT,
  summary        TEXT,
  started_at     INTEGER NOT NULL,
  ended_at       INTEGER
);

-- The replay journal: causes only. Deaths/damage/procs are regenerated by the
-- deterministic engine on replay, never stored.
CREATE TABLE battle_actions (
  battle_id  TEXT NOT NULL REFERENCES battles(id),
  seq        INTEGER NOT NULL,
  controller TEXT NOT NULL,
  action     TEXT NOT NULL,
  PRIMARY KEY (battle_id, seq)
);

-- Chat is not a BattleAction and never touches the engine or state hash.
CREATE TABLE battle_chat (
  battle_id  TEXT NOT NULL REFERENCES battles(id),
  after_seq  INTEGER NOT NULL,
  controller TEXT NOT NULL,
  text       TEXT NOT NULL,
  ts         INTEGER NOT NULL
);

-- Created by db.ts before migrations run (it stores schema_version itself);
-- listed here so the schema file is the complete picture.
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT);
